# mysql
spring:
  datasource:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${DB_URL:jdbc:mysql://localhost:3306/ms-operador}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  application:
    name: ms-operador

# Config de inst
server:
  port: 8087
  
## Configuracion del cliente de Eureka
eureka:
  instance:
    preferIpAddress: false
    hostname: ${HOSTNAME:ms-operador}
    non-secure-port-enabled: false
    secure-port-enabled: true
    non-secure-port: 80
    secure-port: 443
    
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

unir:
  app:
    buscador:
      producto:
        get:
          url: ${PRODUCTO_URL_GET:http://ms-buscador/productos/%s}
        create:
          url: ${PRODUCTO_URL_CREATE:http://ms-buscador/productos}
      productoproveedor:
        get:
          url: ${PPROVEEDOR_URL_CREATE:http://ms-buscador/proveedores/%s/productos/%s}