# mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms-operador
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  application:
    name: ms-operador

# Config de inst
server:
  port: 8087
  
## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-operador

unir:
  app:
    buscador:
      producto:
        get:
          url: http://ms-buscador/productos/%s
        update:
          url: http://ms-buscador/productos/%s
        codigo:
          url: http://ms-buscador/productos?codigo=%s
        create:
          url: http://ms-buscador/productos
      productoproveedor:
        get:
          url: http://ms-buscador/proveedores/%s/productos/%s